Fix: Prevent InvalidOperationException in HandleGameUpdated by using FirstOrDefault
andrew-codes/playnite-web pull request #565
Opened 2024-10-01 10:20 UTC by cvele

- Replaced First() with FirstOrDefault() to handle cases where no matching game is found.
- Added null checks and logging for missing games to avoid unhandled exceptions.
- Ensured graceful handling of updated games and playlist publications.

This is **NOT** tested as I do not have development environment up, we're just being a bit more defensive in cases where game is not found. Usually happens on startup during library update.

Used github editor for contribution, sadly it seems to have messed the formatting since it's reporting this many changes. Only real one is in `HandleGameUpdated`

2024-10-01 10:21 UTC, cvele commented
Fixes #564

2024-10-01 16:19 UTC, andrew-codes commented
This is excellent! Thank you for your contribution. I'll check it out, format it in a new commit and verify via local testing. If all goes well, I'll merge the PR. Thanks again!

2024-10-04 08:22 UTC, cvele commented
Fixes #567 too. Formatting issue persists.

2024-10-04 12:33 UTC, andrew-codes requested changes
Excellent work! Thank you for the contribution! 💯 

The formatting is due to the addition/removal of carriage return characters. I checked out the PR on my Windows environment and the formatting is not corrected or changed, so we are fine in that regard.

I couldn't make these changes to your remote, but the only issue I see is the usage of Logger methods directly. We'll need to instantiate a class member for the logger. I've done so and made other casing changes as suggestions to this PR. Once these changes are made, I'll merge the PR. Thanks again!

2024-10-04 12:33 UTC, andrew-codes commented on apps/PlayniteWebPlugin/src/PlayniteWeb.cs
> +          Logger.Debug($"Game with ID {e} not found for uninstall.");
Logger methods are not static. To correct this, we'll need to instantiate a a private logger class member and use it in place of `Logger.*`.

I'll add a separate comment for the logger class member addition.

```suggestion
          logger.Debug($"Game with ID {e} not found for uninstall.");

```

2024-10-04 12:33 UTC, andrew-codes commented on apps/PlayniteWebPlugin/src/PlayniteWeb.cs
> +    private readonly IManageTopics topicManager;
```suggestion
    private readonly IManageTopics topicManager;
    private ILogger logger = LogManager.GetLogger();

```

2024-10-04 12:33 UTC, andrew-codes commented on apps/PlayniteWebPlugin/src/PlayniteWeb.cs
> +        Logger.Error(ex, $"Error occurred in Subscriber_OnUninstallGameRequest for Game ID {e}.");
```suggestion
        logger.Error(ex, $"Error occurred in Subscriber_OnUninstallGameRequest for Game ID {e}.");

```

2024-10-04 12:33 UTC, andrew-codes commented on apps/PlayniteWebPlugin/src/PlayniteWeb.cs
> +          Logger.Debug($"Game with ID {e} not found for installation.");
```suggestion
          logger.Debug($"Game with ID {e} not found for installation.");

```

2024-10-04 12:33 UTC, andrew-codes commented on apps/PlayniteWebPlugin/src/PlayniteWeb.cs
> +        Logger.Error(ex, $"Error occurred in Subscriber_OnInstallGameRequest for Game ID {e}.");
```suggestion
        logger.Error(ex, $"Error occurred in Subscriber_OnInstallGameRequest for Game ID {e}.");

```

2024-10-04 12:33 UTC, andrew-codes commented on apps/PlayniteWebPlugin/src/PlayniteWeb.cs
> +          Logger.Debug("No matching games found for update.");
```suggestion
          logger.Debug("No matching games found for update.");

```

2024-10-04 12:33 UTC, andrew-codes commented on apps/PlayniteWebPlugin/src/PlayniteWeb.cs
> +        Logger.Error(ex, "Error occurred in HandleGameUpdated method.");
```suggestion
        logger.Error(ex, "Error occurred in HandleGameUpdated method.");

```

2024-10-05 19:02 UTC, andrew-codes approved these changes
I'll test this once home and merge. Thanks!

2024-10-06 18:03 UTC, merged